# Gensis Block config 

Organizations:
    - &Orderer1Org
        Name: Orderer1Org
        ID: Orderer1MSP
        MSPDir: ./organizations/ordererOrganizations/orderer1.maybe.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Orderer1MSP.member', 'Org1MSP.peer', 'Org2MSP.peer')"
            Writers:
                Type: Signature
                Rule: "OR('Orderer1MSP.member', 'Org1MSP.peer', 'Org2MSP.peer')"
            Admins:
                Type: Signature
                Rule: "OR('Orderer1MSP.admin')"

        OrdererEndpoints:
            - orderer0.orderer1.maybe.com:7050

    - &Orderer2Org
        Name: Orderer2Org
        ID: Orderer2MSP
        MSPDir: ./organizations/ordererOrganizations/orderer2.maybe.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Orderer2MSP.member', 'Org1MSP.peer', 'Org2MSP.peer')"
            Writers:
                Type: Signature
                Rule: "OR('Orderer2MSP.member', 'Org1MSP.peer', 'Org2MSP.peer')"
            Admins:
                Type: Signature
                Rule: "OR('Orderer2MSP.admin')"

        OrdererEndpoints:
            - orderer0.orderer2.maybe.com:7050

    - &Org1
        Name: Org1MSP
        ID: Org1MSP
        MSPDir: ./organizations/peerOrganizations/org1.maybe.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org1MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org1MSP.peer', 'Org2MSP.client')"

        AnchorPeers:
            - Host: peerx.org1.maybe.com
              Port: 7051

    - &Org2
        Name: Org2MSP
        ID: Org2MSP
        MSPDir: ./organizations/peerOrganizations/org2.maybe.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org2MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org2MSP.peer', 'Org2MSP.client')"

        AnchorPeers:
            - Host: peer0.org2.maybe.com
              Port: 7051


Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true


# Application Channel
Application: &ApplicationDefaults
    Organizations:

    Policies:
        Readers:
            # Type: ImplicitMeta
            # Rule: "ANY Readers"
            Type: Signature
            Rule: "OR('Org1MSP.peer', 'Org2MSP.peer', 'Org1MSP.member', 'Org1MSP.client', 'Org2MSP.member', 'Org2MSP.client')"
        Writers:
            # Type: ImplicitMeta
            # Rule: "ANY Writers"
            Type: Signature
            Rule: "OR('Org1MSP.peer', 'Org2MSP.peer', 'Org1MSP.member', 'Org1MSP.client', 'Org2MSP.member', 'Org2MSP.client')"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            # TODO
            # Type: Signature
            # Rule: "OR('Org1MSP.peer', 'Org2MSP.peer', 'Org1MSP.member', 'Org2MSP.member')"
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            # Type: Signature
            # Rule: "OR('Org1MSP.peer', 'Org2MSP.peer', 'Org1MSP.member', 'Org2MSP.member')"
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities


Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer0.orderer1.maybe.com:7050
        - orderer0.orderer2.maybe.com:7050
    EtcdRaft:
        Options:
            TickInterval: "500ms"
            ElectionTick: 10
            HeartbeatTick: 1
            MaxInflightBlocks: 5
            SnapShotIntervalSize: 16777216
        Consenters:
            - Host: orderer0.orderer1.maybe.com
              Port: 7050
              ClientTLSCert: ./organizations/ordererOrganizations/orderer1.maybe.com/orderers/orderer0.orderer1.maybe.com/tls/server.crt
              ServerTLSCert: ./organizations/ordererOrganizations/orderer1.maybe.com/orderers/orderer0.orderer1.maybe.com/tls/server.crt
            - Host: orderer0.orderer2.maybe.com
              Port: 7050
              ClientTLSCert: ./organizations/ordererOrganizations/orderer2.maybe.com/orderers/orderer0.orderer2.maybe.com/tls/server.crt
              ServerTLSCert: ./organizations/ordererOrganizations/orderer2.maybe.com/orderers/orderer0.orderer2.maybe.com/tls/server.crt

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Organizations:
        - *Orderer1Org
        - *Orderer2Org

    Policies:
        Readers:
            Type: Signature
            Rule: "OR('Org1MSP.peer', 'Org2MSP.peer', 'Org1MSP.member', 'Org2MSP.member')"
            # Type: ImplicitMeta
            # Rule: "ANY Readers"
        Writers:
            #Type: Signature
            #Rule: "OR('Org1MSP.peer', 'Org2MSP.peer', 'Org1MSP.member', 'Org2MSP.member')"
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"


Channel: &ChannelDefaults
    Policies:
        # Who may invoke the 'Deliver' API
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        # Who may invoke the 'Broadcast' API
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        # By default, who may modify elements at this config level
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities


Profiles:
    TwoPeersGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1
                    - *Org2
    TwoPeersChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
            Capabilities:
                <<: *ApplicationCapabilities

