

OrdererOrgs:
  - Name: orderer1
    Domain: orderer1.maybe.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - orderer1.com

  - Name: orderer2
    Domain: orderer2.maybe.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - orderer2.com

PeerOrgs:
  - Name: org1
    Domain: org1.maybe.com
    EnableNodeOUs: true
    Specs:
        - Hostname: peerx

  - Name: org2
    Domain: org2.maybe.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - peer2.com
    Users:
      Count: 1

