

OrdererOrgs:
  - Name: orderer1
    Domain: orderer1.maybe.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost # for port mapping address

  - Name: orderer2
    Domain: orderer2.maybe.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost

PeerOrgs:
  - Name: org1
    Domain: org1.maybe.com
    EnableNodeOUs: true
    Specs:
        - Hostname: peerx
          SANS:
              - localhost

  - Name: org2
    Domain: org2.maybe.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1

